services:
  db:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1433:1433"
    user: root
    environment:
      SA_PASSWORD: "sa@123456"
      MSSQL_PID: Developer
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    volumes:
        - ../data/sqlvolume:/var/opt/mssql
networks:
  default:
    name: keyboard-network
    external: true
