services:
  db:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "sa@123456"
      MSSQL_PID: Developer
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
networks:
  default:
    name: keyboard-network
    external: true
